/**
 * Experience Page Content Model
 * Structured description of the experience page content for minimap rendering
 */

import { createPortfolioContent } from '../PortfolioContentModel';
import { HeadingNode, ParagraphNode, ListItemNode, DividerNode, SectionNode, LayoutNode } from '../../types/layout';

/**
 * Generate the structured content model for the experience page
 */
export function getExperiencePageContent() {
  const builder = createPortfolioContent('/experience');

  // Main title
  const title: HeadingNode = {
    type: 'heading',
    id: 'experience-title',
    x: 0,
    y: 0,
    width: 700,
    height: 48,
    importance: 1,
    level: 1,
    text: 'EXPERIENCE LOG',
  };

  // Section: Ragastra
  const ragastraSection: SectionNode = {
    type: 'section',
    id: 'ragastra-section',
    x: 0,
    y: 64,
    width: 700,
    height: 0,
    importance: 0.8,
    title: 'Ragastra',
    children: [
      {
        type: 'heading' as const,
        id: 'ragastra-heading',
        x: 0,
        y: 0,
        width: 700,
        height: 40,
        importance: 0.9,
        level: 2,
        text: 'Ragastra - Core Engineer',
      },
      {
        type: 'paragraph' as const,
        id: 'ragastra-p1',
        x: 0,
        y: 56,
        width: 700,
        height: 48,
        importance: 0.5,
        lineCount: 2,
        hasLinks: false,
      },
      {
        type: 'heading' as const,
        id: 'ragastra-focus-heading',
        x: 0,
        y: 120,
        width: 700,
        height: 32,
        importance: 0.7,
        level: 3,
        text: 'KEY FOCUS',
      },
      {
        type: 'list-item' as const,
        id: 'ragastra-l1',
        x: 0,
        y: 168,
        width: 700,
        height: 24,
        importance: 0.4,
        indentLevel: 0,
        hasSubItems: false,
      },
      {
        type: 'list-item' as const,
        id: 'ragastra-l2',
        x: 0,
        y: 200,
        width: 700,
        height: 24,
        importance: 0.4,
        indentLevel: 0,
        hasSubItems: false,
      },
      {
        type: 'list-item' as const,
        id: 'ragastra-l3',
        x: 0,
        y: 232,
        width: 700,
        height: 24,
        importance: 0.4,
        indentLevel: 0,
        hasSubItems: false,
      },
      {
        type: 'heading' as const,
        id: 'ragastra-contrib-heading',
        x: 0,
        y: 272,
        width: 700,
        height: 32,
        importance: 0.7,
        level: 3,
        text: 'KEY CONTRIBUTIONS',
      },
      {
        type: 'list-item' as const,
        id: 'ragastra-c1',
        x: 0,
        y: 320,
        width: 700,
        height: 24,
        importance: 0.4,
        indentLevel: 0,
        hasSubItems: false,
      },
      {
        type: 'list-item' as const,
        id: 'ragastra-c2',
        x: 0,
        y: 352,
        width: 700,
        height: 24,
        importance: 0.4,
        indentLevel: 0,
        hasSubItems: false,
      },
      {
        type: 'list-item' as const,
        id: 'ragastra-c3',
        x: 0,
        y: 384,
        width: 700,
        height: 24,
        importance: 0.4,
        indentLevel: 0,
        hasSubItems: false,
      },
      {
        type: 'list-item' as const,
        id: 'ragastra-c4',
        x: 0,
        y: 416,
        width: 700,
        height: 24,
        importance: 0.4,
        indentLevel: 0,
        hasSubItems: false,
      },
      {
        type: 'divider' as const,
        id: 'ragastra-divider',
        x: 0,
        y: 456,
        width: 700,
        height: 20,
        importance: 0.3,
        thickness: 1,
      },
    ],
  };

  // Section: Arceus Labs
  const arceusSection: SectionNode = {
    type: 'section',
    id: 'arceus-section',
    x: 0,
    y: 540,
    width: 700,
    height: 0,
    importance: 0.8,
    title: 'Arceus Labs',
    children: [
      {
        type: 'heading' as const,
        id: 'arceus-heading',
        x: 0,
        y: 0,
        width: 700,
        height: 40,
        importance: 0.9,
        level: 2,
        text: 'Arceus Labs - Founder',
      },
      {
        type: 'paragraph' as const,
        id: 'arceus-p1',
        x: 0,
        y: 56,
        width: 700,
        height: 48,
        importance: 0.5,
        lineCount: 2,
        hasLinks: false,
      },
      {
        type: 'heading' as const,
        id: 'arceus-mission-heading',
        x: 0,
        y: 120,
        width: 700,
        height: 32,
        importance: 0.7,
        level: 3,
        text: 'MISSION',
      },
      {
        type: 'list-item' as const,
        id: 'arceus-l1',
        x: 0,
        y: 168,
        width: 700,
        height: 24,
        importance: 0.4,
        indentLevel: 0,
        hasSubItems: false,
      },
      {
        type: 'list-item' as const,
        id: 'arceus-l2',
        x: 0,
        y: 200,
        width: 700,
        height: 24,
        importance: 0.4,
        indentLevel: 0,
        hasSubItems: false,
      },
      {
        type: 'divider' as const,
        id: 'arceus-divider',
        x: 0,
        y: 240,
        width: 700,
        height: 20,
        importance: 0.3,
        thickness: 1,
      },
    ],
  };

  // Section: Grosity
  const grositySection: SectionNode = {
    type: 'section',
    id: 'grosity-section',
    x: 0,
    y: 800,
    width: 700,
    height: 0,
    importance: 0.8,
    title: 'Grosity',
    children: [
      {
        type: 'heading' as const,
        id: 'grosity-heading',
        x: 0,
        y: 0,
        width: 700,
        height: 40,
        importance: 0.9,
        level: 2,
        text: 'Grosity - Early-Stage Founding Engineer',
      },
      {
        type: 'heading' as const,
        id: 'grosity-contrib-heading',
        x: 0,
        y: 56,
        width: 700,
        height: 32,
        importance: 0.7,
        level: 3,
        text: 'KEY CONTRIBUTIONS',
      },
      {
        type: 'list-item' as const,
        id: 'grosity-l1',
        x: 0,
        y: 104,
        width: 700,
        height: 24,
        importance: 0.4,
        indentLevel: 0,
        hasSubItems: false,
      },
      {
        type: 'list-item' as const,
        id: 'grosity-l2',
        x: 0,
        y: 136,
        width: 700,
        height: 24,
        importance: 0.4,
        indentLevel: 0,
        hasSubItems: false,
      },
      {
        type: 'list-item' as const,
        id: 'grosity-l3',
        x: 0,
        y: 168,
        width: 700,
        height: 24,
        importance: 0.4,
        indentLevel: 0,
        hasSubItems: false,
      },
      {
        type: 'divider' as const,
        id: 'grosity-divider',
        x: 0,
        y: 208,
        width: 700,
        height: 20,
        importance: 0.3,
        thickness: 1,
      },
    ],
  };

  // Hardware Projects Section
  const hardwareSection: SectionNode = {
    type: 'section',
    id: 'hardware-section',
    x: 0,
    y: 1028,
    width: 700,
    height: 0,
    importance: 0.8,
    title: 'Hardware Projects',
    children: [
      {
        type: 'heading' as const,
        id: 'smart-blind-heading',
        x: 0,
        y: 0,
        width: 700,
        height: 32,
        importance: 0.8,
        level: 2,
        text: 'Smart Blind Stick',
      },
      {
        type: 'heading' as const,
        id: 'smart-blind-deliverables-heading',
        x: 0,
        y: 40,
        width: 700,
        height: 28,
        importance: 0.6,
        level: 3,
        text: 'KEY DELIVERABLES',
      },
      {
        type: 'list-item' as const,
        id: 'smart-blind-l1',
        x: 0,
        y: 84,
        width: 700,
        height: 24,
        importance: 0.4,
        indentLevel: 0,
        hasSubItems: false,
      },
      {
        type: 'list-item' as const,
        id: 'smart-blind-l2',
        x: 0,
        y: 116,
        width: 700,
        height: 24,
        importance: 0.4,
        indentLevel: 0,
        hasSubItems: false,
      },
      {
        type: 'list-item' as const,
        id: 'smart-blind-l3',
        x: 0,
        y: 148,
        width: 700,
        height: 24,
        importance: 0.4,
        indentLevel: 0,
        hasSubItems: false,
      },
      {
        type: 'divider' as const,
        id: 'hardware-divider1',
        x: 0,
        y: 188,
        width: 700,
        height: 20,
        importance: 0.3,
        thickness: 1,
      },
      {
        type: 'heading' as const,
        id: 'zephyr-heading',
        x: 0,
        y: 224,
        width: 700,
        height: 32,
        importance: 0.8,
        level: 2,
        text: 'Zephyr Station',
      },
      {
        type: 'heading' as const,
        id: 'zephyr-deliverables-heading',
        x: 0,
        y: 264,
        width: 700,
        height: 28,
        importance: 0.6,
        level: 3,
        text: 'KEY DELIVERABLES',
      },
      {
        type: 'list-item' as const,
        id: 'zephyr-l1',
        x: 0,
        y: 308,
        width: 700,
        height: 24,
        importance: 0.4,
        indentLevel: 0,
        hasSubItems: false,
      },
      {
        type: 'list-item' as const,
        id: 'zephyr-l2',
        x: 0,
        y: 340,
        width: 700,
        height: 24,
        importance: 0.4,
        indentLevel: 0,
        hasSubItems: false,
      },
      {
        type: 'list-item' as const,
        id: 'zephyr-l3',
        x: 0,
        y: 372,
        width: 700,
        height: 24,
        importance: 0.4,
        indentLevel: 0,
        hasSubItems: false,
      },
      {
        type: 'divider' as const,
        id: 'hardware-divider2',
        x: 0,
        y: 412,
        width: 700,
        height: 20,
        importance: 0.3,
        thickness: 1,
      },
    ],
  };

  // Education Section
  const educationSection: SectionNode = {
    type: 'section',
    id: 'education-section',
    x: 0,
    y: 1460,
    width: 700,
    height: 0,
    importance: 0.8,
    title: 'Education',
    children: [
      {
        type: 'heading' as const,
        id: 'education-heading',
        x: 0,
        y: 0,
        width: 700,
        height: 40,
        importance: 0.9,
        level: 2,
        text: 'Thapar Institute (TIET)',
      },
      {
        type: 'paragraph' as const,
        id: 'education-p1',
        x: 0,
        y: 56,
        width: 700,
        height: 48,
        importance: 0.5,
        lineCount: 2,
        hasLinks: false,
      },
    ],
  };

  builder.addNodes([
    title,
    ragastraSection,
    arceusSection,
    grositySection,
    hardwareSection,
    educationSection,
  ]);

  return builder.build();
}
